Add missing fields for Security context  and secrets
twuni/docker-registry.helm pull request #102
Opened 2023-03-28 15:12 UTC by erikfuego

Due to PodSecurity policies in place after CIS hardening my cluster, I had to add the following to the pod or container security context:
```
runAsNonRoot: true
seccompProfile:
  type: "RuntimeDefault"
allowPrivilegeEscalation: false
capabilities:
  drop:
  - ALL
```
With the current securityContext implementation, only `securityContext.fsGroup` and `securityContext.runAsUser` were included. This change adds the ability to include everything in the `securityContext` provided. It also removes the `enabled` parameter which is unnecessary to me because we can just check if anything in the `securityContext` exists.

I added a `containerSecurityContext` to help differentiate between adding these fields for a container or the service itself. If `securityContext` is added for the service, PodSecurity fails because it specifically asks to be added to the container level.

This also adds a missing field for secrets called `secretRef` for s3.

2023-04-10 17:43 UTC, schinmai-akamai commented
+1 to this - would love to have the ability to pass securityContexts

2023-07-11 01:47 UTC, joshsizer commented
+1 this is a crucial feature

2023-07-11 01:58 UTC, joshsizer commented on templates/deployment.yaml
> +        {{- end }}
```suggestion
      {{- end }}
```

2023-07-11 12:59 UTC, Mercbot7 commented
This is a needed feature for us as well!

2023-11-27 18:00 UTC, erikfuego commented
sorry everyone! i was on paternal leave. hoping this gets merged soon

2024-01-31 21:51 UTC, joshsizer approved these changes
LGTM

2024-01-31 21:57 UTC, joshsizer commented
@canterberry Could we get an `Approving review`?

This MR looks good to me, and it's backwards compatible. Also, happy to become a maintainer for this repo if you need some help going through these issues.

2024-02-01 15:10 UTC, joshsizer requested changes
@erikfuego I realize this is not backwards compatible as of now, if people have securityContext disabled, this update will now automatically enable it which may be undesired and breaking (since there are default fields for securityContext set).

In the case that someone already has it enabled, you receive the following warning when installing:

```
W0201 10:03:19.051240    7376 warnings.go:70] unknown field "spec.template.spec.securityContext.enabled"
```

I've suggested some ways to work around this by keeping the enabled field, and omitting it when populating the securityContext sections.

I was using the [Bitnami MongoDB chart](https://github.com/bitnami/charts/blob/4369898d264d231606e394b59ed4b3d926155d4c/bitnami/mongodb/templates/standalone/dep-sts.yaml#L79-L81) as a basis

2024-02-01 15:10 UTC, joshsizer commented on templates/deployment.yaml
> +          {{- if .Values.containerSecurityContext }}
```suggestion
          {{- if .Values.containerSecurityContext.enabled }}
```

2024-02-01 15:10 UTC, joshsizer commented on values.yaml
>    fsGroup: 1000
```suggestion
  fsGroup: 1000
  
containerSecurityContext:
  enabled: false
```

2024-02-01 16:06 UTC, erikfuego commented
> @erikfuego I realize this is not backwards compatible as of now, if people have securityContext disabled, this update will now automatically enable it which may be undesired and breaking (since there are default fields for securityContext set).
> 
> In the case that someone already has it enabled, you receive the following warning when installing:
> 
> ```
> W0201 10:03:19.051240    7376 warnings.go:70] unknown field "spec.template.spec.securityContext.enabled"
> ```
> 
> I've suggested some ways to work around this by keeping the enabled field, and omitting it when populating the securityContext sections.
> 
> I was using the [Bitnami MongoDB chart](https://github.com/bitnami/charts/blob/4369898d264d231606e394b59ed4b3d926155d4c/bitnami/mongodb/templates/standalone/dep-sts.yaml#L79-L81) as a basis

Yeah thats a good point. Can you confirm that all the changes you suggested are in? The CI tests are failing. Im also going to test this locally with the values I set for the chart

2024-02-01 16:16 UTC, erikfuego commented
@joshsizer I reverted the changes you made to the `containerSecurityContext` because thats a new field I added to make the securityContext work for containers. And accepted your changes to leave securityContext along with the `enabled` field. The CI now passes

2024-02-01 17:50 UTC, joshsizer commented
> @joshsizer I reverted the changes you suggested for `containerSecurityContext` because thats a new field I added to make the securityContext work for containers. And accepted your changes to keep the `enabled` field for securityContext and omit it when populating securityContext

Awesome! I wonder, would it be good to keep the changes for containerSecurityContext, so that the schemas for each section are similar? I see either option as viable, but lean towards keeping them similar. I think lint was failing because we would have to add in to `values.yaml`

```yaml
containerSecurityContext:
  enabled: false
```

2024-02-01 18:14 UTC, erikfuego commented
> > @joshsizer I reverted the changes you suggested for `containerSecurityContext` because thats a new field I added to make the securityContext work for containers. And accepted your changes to keep the `enabled` field for securityContext and omit it when populating securityContext
> 
> Awesome! I wonder, would it be good to keep the changes for containerSecurityContext, so that the schemas for each section are similar? I see either option as viable, but lean towards keeping them similar. I think lint was failing because we would have to add in to `values.yaml`
> 
> ```yaml
> containerSecurityContext:
>   enabled: false
> ```

I prefer the pattern where `enabled` is not used because otherwise its an extra value to worry about. But if you want to use `enabled`, feel free to suggest the changes and I can apply them

2024-02-01 20:15 UTC, erikfuego commented
sorry about that weird merge, I merged this branch into a colleagues forked repo to test these changes, and for some reason his changes were merged into my branch.

2024-02-02 16:24 UTC, erikfuego commented
> The last change we need is to add to values.yaml:
> 
> ```yaml
> containerSecurityContext:
>   enabled: false
> ```

that broke the CI

2024-02-02 19:44 UTC, joshsizer commented
> > The last change we need is to add to values.yaml:
> > ```yaml
> > containerSecurityContext:
> >   enabled: false
> > ```
> 
> that broke the CI

Could you add into values.yaml

```
containerSecurityContext:
  enabled: false
```

That will fix the CI.

I'm not sure I can push to this branch

2024-02-05 15:53 UTC, joshsizer approved these changes
LGTM

@canterberry Can you review this as well?

2024-02-20 22:43 UTC, erikfuego commented
> LGTM
> 
> @canterberry Can you review this as well?

wanted to bumb this. Thanks!

2024-03-02 18:39 UTC, joshsizer commented
@erikfuego Would you be able to recommit with signed commits? I am now a maintainer, and can approve and merge, but this repository is setup to only allow signed commits

2024-03-05 19:31 UTC, vyas-n approved these changes

2024-03-05 19:32 UTC, vyas-n commented
@joshsizer

Not sure what the protocol should be moving forward, but I'm also a maintainer and I can now merge if you'd like.

2024-03-05 19:52 UTC, joshsizer approved these changes

2024-03-05 19:54 UTC, joshsizer commented
> @joshsizer
> 
> Not sure what the protocol should be moving forward, but I'm also a maintainer and I can now merge if you'd like.

Let's do it!

2024-03-05 19:59 UTC, merged