Allow to specify resources block for garbage-collector
twuni/docker-registry.helm pull request #124
Opened 2024-04-15 11:13 UTC by baznikin

2024-04-22 21:25 UTC, vyas-n approved these changes

2024-04-22 21:27 UTC, vyas-n requested changes
Thanks @baznikin,

Would you mind signing your commits with a GPG Key? (or SSH Key)

There's a guide on GitHub on how to sign commits: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

As well as this guide for how to sign and push up previous commits: https://stackoverflow.com/a/15667644/8401320

Once you've resigned your commit, you can push it up with a `git push -f` and we can review it

2024-04-26 11:26 UTC, baznikin commented
@vyas-n done!

2024-04-27 16:36 UTC, vyas-n approved these changes

2024-04-27 16:36 UTC, merged

2024-04-27 16:36 UTC, vyas-n commented
Thanks @baznikin!