Fix for issue number 19, current api version and previous api version…
twuni/docker-registry.helm pull request #27
Opened 2021-09-06 20:22 UTC by karezza

The current version of kubernetes will be unable to install this helm chart.  Update Ingress api version to the current stable version used by kubernetes.  Update the else version to use the previous beta version.

2021-09-09 13:20 UTC, tarioch commented
Careful, there is more required than just changing the version, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

2021-09-09 22:17 UTC, vivekpatani commented
@karezza 

```
{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "docker-registry.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $path := .Values.ingress.path -}}
apiVersion: {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }} networking.k8s.io/v1 {{- else }} extensions/v1 {{- end }}
kind: Ingress
metadata:
  name: {{ template "docker-registry.fullname" . }}
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
```

The `service` section towards the end is broken up into multiple entities too, and `PathType: <ImplementationSpecific>` is a neccesary field. I'm not sure if these are the only changes needed, but this worked for me.

2021-09-27 07:02 UTC, canterberry approved these changes
Assuming that `extensions/v1beta1` is EOL, which I think it effectively is at this point, I don't mind breaking support for it.

2021-09-27 15:47 UTC, kervel commented
i think https://github.com/Kapernikov/docker-registry.helm/commit/22eca8f7680c1289dd094ffe36f44fbbedde14f5 this is what is needed ...

2021-09-28 04:24 UTC, karezza commented
Added 'ingressClassName' and also defined a default value in values.yaml, it is my understanding that although an ingress can be created without this with a default being automatically selected, instead people should always have it defined in their ingress going forward and not in the annotations (where this was sometimes happening before, but not in a clearly defined way).

2021-09-28 06:46 UTC, kervel commented
i went  thru the kubernetes history to see how long networking.k8s.io/v1 is already there, and apparently its only there since 1.19 (which is 1 year ago). actually astonished that kubernetes breaks compat with old API only 1 year after releasing the new one...

so i guess it makes sense to try to also support the v1beta1.

2021-10-10 08:58 UTC, ElArtista commented
I suppose #33 is relevant to this?

2021-11-11 20:57 UTC, DBarthe commented
Hello !

Could we just add :
```
apiVersion: {{- if $apiVersion.Has "networking.k8s.io/v1" }} networking.k8s.io/v1 {{- else if $apiVersion.Has "networking.k8s.io/v1beta1" }} networking.k8s.io/v1beta1 {{- else }} extensions/v1beta1 {{- end }}
```
So that we can support 1.22 while not breaking any older version ?

2021-11-23 10:21 UTC, ElArtista approved these changes

2021-12-11 21:06 UTC, canterberry commented on templates/ingress.yaml
> +{{- $apiVersion := .Capabilities.APIVersions -}}
Should be `$apiVersions`

2021-12-11 21:07 UTC, canterberry commented on values.yaml
> +  ingressClassName: nginx
`ingress.ingressClassName` is redundant -- instead, should be `ingress.className`.

Please add documentation for this value to the README as well.

2021-12-11 21:09 UTC, canterberry requested changes
Thank you for this PR. I have a couple of very small requests, but aside from that this changeset looks good. In addition to looking over the changeset, I ran through the exercise of making the same set of changes by cross-referencing against the `kubectl explain ingress` output on a modern cluster. Line-for-line, I came to pretty much the same result.

2022-01-04 04:23 UTC, canterberry commented
Superceded by #48.

2022-01-04 04:23 UTC, closed without merging